### ISSUE TITLE
Flash detection not working

### ISSUE THREAD

**Issue by jxp** [mozilla/shumway#113] opened 2013-02-26 16:56 UTC
I have just tested Shumway on a site and saw no flash content.
This was caused by the site using a Flash detection script that checked 
```
navigator.plugins["Shockwave Flash"].description 
```
to ensure a compatible version of Flash could be found.

I'm not sure what can be done about this as the plugins collection is read-only. The only thing that leaps to mind is having a dummy plug-in that has a name of Shockwave Flash, but that seems messy

**Comment by yurydelendik** [comment] 2015-05-13 18:35
Closing as duplicate of bug 840439 (will be tracking there)

**Closed by yurydelendik** 2015-05-13 18:35 UTC
Labels: feature-request

**Comment by ariscop** [comment] 2016-03-12 04:31
[bug 867626](https://bugzilla.mozilla.org/show_bug.cgi?id=867626) has been resolved incomplete, should this bug be reopened? having sites refuse to load swf files somewhat limits shumway as a flash alternative
