### ISSUE TITLE
FF 40 disable Shumway

### ISSUE THREAD

**Issue by toblerone1963** [mozilla/shumway#2342] opened 2015-08-16 09:59 UTC
Hello, Shumway is [not signed](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct), so FF40 disabled it. Can you change that ?

![screen](https://cloud.githubusercontent.com/assets/5781292/9292841/1c06bf3a-440e-11e5-91be-eb500fe60aba.png)

Thanks, keep up the good work !

**Comment by timvandermeij** [comment] 2015-08-16 12:06
This is a duplicate of #2329.

**Comment by timvandermeij** [comment] 2015-12-21 12:32
@yurydelendik This issue can be closed now that Shumway is signed too.

**Comment by yurydelendik** [comment] 2015-12-21 12:47
Closing as duplicate of #2329.

**Closed by yurydelendik** 2015-12-21 12:47 UTC
