### ISSUE TITLE
Addon blocked; needs signing

### ISSUE THREAD

**Issue by toothbrush7777777** [mozilla/shumway#2329] opened 2015-08-07 14:18 UTC
Shumway is currently blocked in Firefox Developer Edition since it is not signed.

![shumway blocked](https://cloud.githubusercontent.com/assets/8356617/9137766/e086ddde-3d17-11e5-802e-e4c911de1cba.jpg)

![shumway blocked 2](https://cloud.githubusercontent.com/assets/8356617/9137794/1024a26a-3d18-11e5-972e-16bd511dddc9.jpg)

Could Shumway be signed so that it will work in current versions of Firefox?

**Comment by timvandermeij** [comment] 2015-08-07 19:21
Referencing the PDF.js issue here too as both projects suffer from this at the moment: #6137

**Comment by Glubzor** [comment] 2015-08-14 12:03
Within FF 41.0b1 addon signing is now mandatory !

**Comment by timvandermeij** [comment] 2015-08-14 17:58
We are aware of this, also on the PDF.js side. The problem is that developers of the add-on signing platform do not have an API yet for us to sign the add-ons with, so it is unsure how we should proceed with this.

**Comment by samatjain** [comment] 2015-08-21 22:45
Workaround is to go into about:config and set `` xpinstall.signatures.required`` to ``false``; Firefox will let you install unsigned extensions again.

**Comment by omega3** [comment] 2015-08-24 14:04
Workaround doesn't work. I still get information that it is not signed. And I can't play flash files.

**Comment by omega3** [comment] 2015-08-25 11:01
Why Shumway is not yet added to official Mozilla add-ons repository so that they can sign it?

I still get information in Firefox that it is not signed and it is disabled. I can't watch video. Please add it to official Firefox add-ons repository.

**Comment by meteormatt** [comment] 2015-08-27 03:33
:+1:

**Comment by strugee** [comment] 2015-09-04 00:19
> Why Shumway is not yet added to official Mozilla add-ons repository so that they can sign it?

Presumably because it's still experimental and changes a lot. Too fast for AMO.

**Comment by tschneidereit** [comment] 2015-09-04 15:21
>
> Why Shumway is not yet added to official Mozilla add-ons repository so
> that they can sign it?
>
> Presumably because it's still experimental and changes a lot. Too fast for
> AMO.
>
That is exactly right: AMO doesn't yet have an API for doing the signing,
so we'd have to do it manually. This is error-prone and would mean that
we'd be quite likely to leave outdated versions up, so for now we're
punting on it.

**Comment by cm-mc** [comment] 2015-09-08 17:03
So if AMO doesn't have an API for signing yet, why is it mandatory already - any adults in charge at Mozilla?

**Comment by freddyb** [comment] 2015-09-10 20:02
Adblock Plus used to have a development (aka beta) version on their own domain, which stopped working, because of signing. To solve this they are now uploading their dev version directly to AMO by instrumenting a browser. Their code to do this is open source: https://adblockplus.org/blog/adblock-plus-for-firefox-and-element-hiding-helper-development-builds-now-hosted-on-amo

Wouldn't this be interesting for automatically uploading weekly(?) builds of shumway?

**Comment by timvandermeij** [comment] 2015-09-10 20:05
I also found https://github.com/minj/foxtrick/blob/master/maintainer/dist/amo_upload.py. It's working around the problem, but since there is still no sigining API available, for now that might be a solution (though not a very good one I must admit). Just adding this for the sake of completeness, not directly to consider using it.

**Comment by Nefari0uss** [comment] 2015-11-13 22:45
It's been atleast 2 months since the last post. Are there any updates on this?

**Comment by timvandermeij** [comment] 2015-11-14 20:18
It appears that there is now an API for extension signing: https://olympia.readthedocs.org/en/latest/topics/api/signing.html. Someone needs to look into if we can use this.

**Comment by meteormatt** [comment] 2015-11-25 05:48
Yes. API for extension signing is ready now. Please sign it.
https://blog.mozilla.org/addons/2015/11/20/signing-api-now-available/

**Comment by KKDeep** [comment] 2015-12-14 11:03
Still the issue is present. I can not install the addon from the site.

**Comment by asuh** [comment] 2015-12-15 21:41
As of Firefox 43 which was released today, Shumway is disabled by default and cannot be enabled unless you go into about:config and change xpinstall.signatures.required to false.

However, even if you do that, starting in version 44, this will not work anymore and Shumway will not work until it's signed.

**Comment by KKDeep** [comment] 2015-12-16 06:38
@asuh I'm using Firefox Developer Edition(which is ver 44) & shumway is installed properly. But there are still some sites  such as http://gaana.com/ which are still asking for Adobe Flash .
Isn't Shumway supposed to be complete replacement for the flash?
![gaana](https://cloud.githubusercontent.com/assets/1812737/11833930/ab8f697e-a3ed-11e5-978d-8f3cf0c37a6a.png)
![shumway](https://cloud.githubusercontent.com/assets/1812737/11833929/ab897618-a3ed-11e5-84ea-3a668efb747c.png)

**Comment by asuh** [comment] 2015-12-16 06:42
@KKDeep I can't speak for the developer edition which is supposed to be more relaxed with unsigned add-ons but Shumway on normal FF will not work as of version 44.

Shumway does not replace flash 100% so you will see sites which cannot render, as you show

**Comment by timvandermeij** [comment] 2015-12-21 12:32
@yurydelendik This issue can be closed now that Shumway is signed too.

**Comment by yurydelendik** [comment] 2015-12-21 12:45
Closing as fixed.

**Closed by yurydelendik** 2015-12-21 12:45 UTC

**Comment by omega3** [comment] 2015-12-23 09:51
In Firefox 43 I still see this information: Shumway could not be verified...
Shumway 0.11.617
When I click on 
 http://mozilla.github.io/shumway/extension/firefox/shumway.xpi
it installs current shumway but it still shows Shumway as switched off.

Will Shumway be available on 
https://addons.mozilla.org/pl/firefox/
and updated as any other add-on?

**Comment by SeventhSonOfASeventhSon** [comment] 2015-12-23 10:42
Well, I'm also running Firefox 43 with Shumway 0.11.620, and all is fine here.

**Comment by timvandermeij** [comment] 2015-12-23 12:30
Note that you might need to remove the old add-on first and install the new one afterwards. This is because of the add-on ID change.

**Comment by omega3** [comment] 2015-12-23 20:16
You are correct. It is fine now. Thank you.
